#! /bin/sh

### BEGIN INIT INFO
# Provides:	    i3_desktop
# Required-Start:	$remote_fs $syslog
# Required-Stop:	$remote_fs $syslog
# Default-Start:	S
# Default-Stop:		
# Short-Description:	i3_desktop
### END INIT INFO

set -e

export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"

case "$1" in
  start)
    i3.sh
	;;
  stop)
    chvt 1
	killall -9 Xorg
	;;

  reload|force-reload)
    chvt 1
	killall -9 Xorg
    i3.sh
	;;

  restart)
    chvt 1
	killall -9 Xorg
    i3.sh
	;;

  try-restart)
    chvt 1
	killall -9 Xorg
    i3.sh
	;;

  status)
	;;

  *)
	exit 1
esac

exit 0
