[Desktop Entry]
Name=mate_theme_yuan
Type=X-GNOME-Metatheme
Comment=

[X-GNOME-Metatheme]
GtkTheme=TraditionalOk
MetacityTheme=TraditionalOk
IconTheme=menta
GtkColorScheme=fg_color:#000000000000,bg_color:#eaeaeaeaeaea,text_color:#000000000000,base_color:#ffffffffffff,selected_fg_color:#ffffffffffff,selected_bg_color:#3f1d807c9199,tooltip_fg_color:#000000000000,tooltip_bg_color:#f5f5f5f5b5b5
CursorTheme=default
CursorSize=18
NotificationTheme=nodoka
