#=============================================================================
# init.toml --- Docker config temp file
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
#=============================================================================

[options]
    colorscheme = "pablo"
    colorscheme_bg = "dark"

#    default_indent = 4
    enable_insert_leader=false
    enable_guicolors = false
    relativenumber = false

    statusline_separator = "nil"
    statusline_separator = "bar"

    buffer_index_type = 4
    enable_tabline_filetype_icon = true

    filemanager = "none"
    autocomplete_method = "neocomplcache"
    bootstrap_before = "myspacevim#before"
    bootstrap_after = "myspacevim#after"

#[[custom_plugins]]
#    name = 'neoclide/coc.nvim'
#    merge = 0
#    build =  'yarn install --frozen-lockfile'

[[custom_plugins]]
    name = "Yggdroot/LeaderF"
    build = "./install.sh"

[[custom_plugins]]
    name = 'voldikss/vim-floaterm'

#[[custom_plugins]]
#    name = 'jackguo380/vim-lsp-cxx-highlight'

[[custom_plugins]]
    name = 'APZelos/blamer.nvim'

[[layers]]
    name = "autocomplete"
#    auto_completion_tab_key_behavior = "smart"
    auto_completion_tab_key_behavior = "none"
    auto_completion_delay = 2
#auto_completion_return_key_behavior = "complete"
#auto_completion_complete_with_key_sequence = "enter"
    auto_completion_complete_with_key_sequence_delay = 0.1

#[[layers]]
#    name = 'lsp'
#    filetypes = [
#        'c',
#        'cpp',
#        'map',
#    ]
#    [layers.override_cmd]
#        c = ['ccls', '--log-file=/tmp/ccls.log']
#        cpp = ['ccls', '--log-file=/tmp/ccls.log']
#        map = ['ccls', '--log-file=/tmp/ccls.log']
